#!/usr/bin/env bash
# Renders Formula/ore.rb for a published ore release, for pushing to the
# ore-cli/homebrew-tap tap (upstream has never had Homebrew automation
# in-repo; its `codex` cask lives in Homebrew/homebrew-cask). Adapted from
# the legacy fork's .github/scripts/render-homebrew-formula.sh with the
# ore-cli coordinates. Digests come from the release's SHA256SUMS — the
# fork-added manifest covering every asset (codex-package_SHA256SUMS, the
# upstream-format file install.sh consumes, covers only the package archives);
# a missing digest fails rather than shipping 3 of 4 platforms.
set -euo pipefail

usage() { echo "usage: $0 --version X.Y.Z [--repo owner/name] --out PATH" >&2; exit "${1:-2}"; }

version=""
repo="${GITHUB_REPOSITORY:-ore-cli/ore}"
out=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) version="$2"; shift 2 ;;
    --repo)    repo="$2";    shift 2 ;;
    --out)     out="$2";     shift 2 ;;
    -h|--help) usage 0 ;;
    *) usage ;;
  esac
done
[[ -n "$version" && -n "$out" ]] || usage

tag="ore-v${version}"
base="https://github.com/${repo}/releases/download/${tag}"

sums="$(mktemp)"
trap 'rm -f "$sums"' EXIT
curl -fsSL --retry 3 --retry-delay 2 "${base}/SHA256SUMS" -o "$sums"

digest_for() {
  local asset="$1" line
  line="$(awk -v a="$asset" '$2 == a { print $1 }' "$sums" | head -n 1)"
  [[ -n "$line" ]] || { echo "::error::${asset} is not in ${tag}'s SHA256SUMS" >&2; exit 1; }
  printf '%s' "$line"
}

# The package archive, not the bare binary: rg and the patched zsh included.
mac_arm="codex-package-aarch64-apple-darwin.tar.gz"
mac_x86="codex-package-x86_64-apple-darwin.tar.gz"
linux_arm="codex-package-aarch64-unknown-linux-musl.tar.gz"
linux_x86="codex-package-x86_64-unknown-linux-musl.tar.gz"

# Before the heredoc: `exit 1` in a command substitution only leaves the
# subshell, so an inline digest_for would emit sha256 "" and exit 0.
sha_mac_arm="$(digest_for "$mac_arm")"
sha_mac_x86="$(digest_for "$mac_x86")"
sha_linux_arm="$(digest_for "$linux_arm")"
sha_linux_x86="$(digest_for "$linux_x86")"

mkdir -p "$(dirname "$out")"
cat > "$out" <<RUBY
# Generated by fork/release/render_homebrew_formula.sh. Do not edit by hand.
class Ore < Formula
  desc "Coding agent for the terminal"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${base}/${mac_arm}"
      sha256 "${sha_mac_arm}"
    end
    on_intel do
      url "${base}/${mac_x86}"
      sha256 "${sha_mac_x86}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/${linux_arm}"
      sha256 "${sha_linux_arm}"
    end
    on_intel do
      url "${base}/${linux_x86}"
      sha256 "${sha_linux_x86}"
    end
  end

  def install
    # ore resolves its siblings relative to itself; keep the bundle assembled.
    libexec.install Pathname.glob("{*,.[!.]*}")
    bin.install_symlink libexec/"bin/ore"
    generate_completions_from_executable(libexec/"bin/ore", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ore --version")
  end
end
RUBY

echo "wrote ${out} for ${tag}"
