mod amazon_bedrock;
mod anthropic;
mod auth;
mod bearer_auth_provider;
mod discovered_models;
mod gemini;
mod models_endpoint;
mod provider;
mod shared_state;

pub use amazon_bedrock::is_supported_amazon_bedrock_region;
pub use anthropic::AnthropicModelFacts;
pub use anthropic::anthropic_model_facts;
pub use anthropic::info::ANTHROPIC_API_KEY_ENV_VAR;
pub use anthropic::info::ANTHROPIC_BASE_URL_ENV_VAR;
pub use anthropic::info::ANTHROPIC_DEFAULT_BASE_URL;
pub use anthropic::info::ANTHROPIC_PROVIDER_ID;
pub use anthropic::info::create_anthropic_provider;
pub use auth::AgentIdentitySessionFallback;
pub use auth::ProviderAuthScope;
pub use auth::ResolvedProviderAuth;
pub use auth::auth_provider_from_auth;
pub use auth::auth_provider_from_auth_manager;
pub use auth::unauthenticated_auth_provider;
pub use bearer_auth_provider::BearerAuthProvider;
pub use bearer_auth_provider::BearerAuthProvider as CoreAuthProvider;
pub use codex_model_provider_info::AMAZON_BEDROCK_PROVIDER_ID;
pub use codex_model_provider_info::AMAZON_BEDROCK_RUNTIME_PROVIDER_ID;
pub use codex_model_provider_info::CHATGPT_CODEX_BASE_URL;
pub use codex_protocol::account::ProviderAccount;
pub use gemini::GeminiModelFacts;
pub use gemini::GeminiModelProvider;
pub use gemini::GeminiThinkingBudget;
pub use gemini::gemini_model_facts;
pub use gemini::info::GEMINI_API_KEY_ENV_VAR;
pub use gemini::info::GEMINI_BASE_URL_ENV_VAR;
pub use gemini::info::GEMINI_DEFAULT_BASE_URL;
pub use gemini::info::GEMINI_PROVIDER_ID;
pub use gemini::info::create_gemini_provider;
pub use provider::ModelProvider;
pub use provider::ModelProviderFuture;
pub use provider::ProviderAccountError;
pub use provider::ProviderAccountResult;
pub use provider::ProviderAccountState;
pub use provider::ProviderCapabilities;
pub use provider::ProviderUnauthorizedRecovery;
pub use provider::RemoteCompactionSupport;
pub use provider::SharedModelProvider;
pub use provider::create_model_provider;
